POST http://localhost:3000/users
Content-Type: application/json

{
  "firstname": "David",
  "lastname": "Lopez",
  "phone":"1158983970",
  "password":"password",
  "tosAgreement": true
}
###

GET http://localhost:3000/users?phone=1158983970
token: wwf9bgufahg3ftx6lfyn

###

PUT http://localhost:3000/users
Content-Type: application/json
token: cple5vt3a4f9lsrixg6a

{
  "firstname": "Davinho",
  "phone":"1158983970"
}

###

DELETE http://localhost:3000/users?phone=1158983970
token: 2mj3ln9c0wm4hk9w43lx

###
// Tokens
POST http://localhost:3000/tokens
Content-Type: application/json

{
  "phone":"1158983970",
  "password":"password"
}

###

GET http://localhost:3000/tokens?tokenId=5of4fj1gxthd0db5f665

###

PUT  http://localhost:3000/tokens
Content-Type: application/json

{
  "id":"hapic2tu33ibz1j8pjix",
  "extend":true
}

###

DELETE http://localhost:3000/tokens?id=5of4fj1gxthd0db5f665

###
// Checks
POST http://localhost:3000/checks
Content-Type: application/json
token: 2mj3ln9c0wm4hk9w43lx

{
  "protocol":"http",
  "url":"infobae.com",
  "method":"get",
  "successcodes":[200, 201],
  "timeoutseconds": 3
}

###

GET http://localhost:3000/checks?id=tfam2lt45bep7koy0dy4
token: jmree4ukutfr00ta3e8a

###

PUT  http://localhost:3000/checks
Content-Type: application/json
token: jmree4ukutfr00ta3e8a

{
  "id":"tfam2lt45bep7koy0dy4",
  "protocol":"https",
  "url":"google.com.ar"
}

###

DELETE http://localhost:3000/checks?id=tfam2lt45bep7koy0dy4
token: 18pxrpwt5w5txerfhgmd