POST http://localhost:3000/users
Content-Type: application/json

{
  "firstname": "David",
  "lastname": "Lopez",
  "phone":"1158983970",
  "password":"password",
  "tosAgreement": true
}
###

GET http://localhost:3000/users?phone=1158983970

###

PUT http://localhost:3000/users
Content-Type: application/json

{
  "firstname": "Davicho",
  "phone":"1164894654"
}

###

DELETE http://localhost:3000/users?phone=1158983970

###
// Tokens
POST http://localhost:3000/tokens
Content-Type: application/json

{
  "phone":"1158983970",
  "password":"password"
}

###

GET http://localhost:3000/tokens?tokenId=5of4fj1gxthd0db5f665

###
